# Generated by Django 4.1.7 on 2023-03-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_5', '0002_alter_bouquet_fresh_period_alter_bouquet_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='invoice',
            field=models.FileField(null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
