# Generated by Django 4.1.7 on 2023-03-21 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_8', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamemodel',
            old_name='gender',
            new_name='genre',
        ),
    ]
